[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
champions_nft = "2ALE79amyCadezBPx3yvfbwcrv6zuXzBUJxtiH6PKDzC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
